"""crear tabla deals

Revision ID: a43d170d63c7
Revises: 
Create Date: 2026-09-01 22:14:49.094888
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a43d170d63c7'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('rehab_budget', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('arv', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('ltc', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('monthly_interest_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('points', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('ltv', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('seasoning_months', sa.Integer(), nullable=False),
    sa.Column('closing_costs', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deals')
    # ### end Alembic commands ###
